### ISSUE TITLE
The auto-detection of assests on a rust release seems to have a few issues with assets

### ISSUE THREAD

**Issue by sheldonhull** [aquaproj/registry-tool#135]
## Reproduce

- Run `aqua-registry scaffold dbrgn/tealdeer`

> Note: I'm submitting a fixed registry entry to the registry, so this is just informational on the auto setup of a package.

See the pointy fingers for the issues I specifically noticed on the defaults: 😄
 
```yaml
packages:
  - type: github_release
    repo_owner: dbrgn
    repo_name: tealdeer
    asset: tealdeer-{{.OS}}-{{.Arch}}-musl
    format: raw
    description: A very fast implementation of tldr in Rust
    replacements:
      amd64: x86_64
      darwin: macos
    overrides:
      - goos: darwin
        asset: tealdeer-{{.OS}}-{{.Arch}}
      - goos: windows
        asset: tealdeer-{{.OS}}-{{.Arch}}-msvc
    supported_envs: # 👈🏻👈🏻👈🏻👈🏻👈🏻  This is a bit confusing. All darwin architecture, else only x86 on everything else, is that what this means? As a newer contributor that's a little confusing.
      - darwin
      - amd64
    rosetta2: true
    checksum:
      type: github_release
      asset: tealdeer-windows-x86_64-msvc.exe.sha256 # 👈🏻👈🏻👈🏻👈🏻👈🏻 
      file_format: regexp
      algorithm: sha256
      pattern:
        checksum: "^(\\b[A-Fa-f0-9]{64}\\b)"
        file: "^\\b[A-Fa-f0-9]{64}\\b\\s+(\\S+)$"

```
